export const SESSION_AUTH = 'UMS_auth'
export const SESSION_ROLE = 'role'
export const SESSION_EMPLOYEE_ID = 'employee_id'
export const SESSION_COLLEGE_ID = 'college_id'
export const SESSION_EMPLOYEE_REVIEW = 'emp_preview'
